In [2]:
from __future__ import print_function
import torch

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 8.5899e+09, 0.0000e+00],
        [8.5899e+09, 1.8361e+25, 1.4603e-19],
        [1.6795e+08, 4.7423e+30, 4.7393e+30],
        [9.5461e-01, 4.4377e+27, 1.7975e+19],
        [4.6894e+27, 7.9463e+08, 3.2604e-12]])


In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6736, 0.4678, 0.0070],
        [0.2931, 0.7004, 0.2078],
        [0.1543, 0.2714, 0.9238],
        [0.1202, 0.1846, 0.8034],
        [0.1731, 0.9845, 0.8578]])


In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [8]:

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[ 0.2564, -0.2651, -0.4084],
        [-2.7939, -0.6543,  0.0275],
        [ 0.1183,  0.0957,  0.6747],
        [-0.0579,  1.5866, -2.3462],
        [ 0.5077,  0.0884,  0.7911]])


In [11]:
print(x.size())

torch.Size([5, 3])


In [12]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.8690,  0.1192, -0.1423],
        [-2.2346, -0.2214,  0.4092],
        [ 0.5557,  0.8172,  1.0157],
        [ 0.3199,  1.9385, -2.2303],
        [ 1.1491,  0.5185,  1.3023]])


In [13]:
print(torch.add(x, y))

tensor([[ 0.8690,  0.1192, -0.1423],
        [-2.2346, -0.2214,  0.4092],
        [ 0.5557,  0.8172,  1.0157],
        [ 0.3199,  1.9385, -2.2303],
        [ 1.1491,  0.5185,  1.3023]])


In [14]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.8690,  0.1192, -0.1423],
        [-2.2346, -0.2214,  0.4092],
        [ 0.5557,  0.8172,  1.0157],
        [ 0.3199,  1.9385, -2.2303],
        [ 1.1491,  0.5185,  1.3023]])


In [15]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.8690,  0.1192, -0.1423],
        [-2.2346, -0.2214,  0.4092],
        [ 0.5557,  0.8172,  1.0157],
        [ 0.3199,  1.9385, -2.2303],
        [ 1.1491,  0.5185,  1.3023]])


In [16]:
print(x[:, 1])

tensor([-0.2651, -0.6543,  0.0957,  1.5866,  0.0884])


In [17]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [20]:
x = torch.randn(34534)
print(x)
print(x[0].item())

tensor([-0.0012, -0.0556,  0.5034,  ...,  0.2988, -0.5558, -0.3937])
-0.00118167360778898


In [21]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [22]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [23]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [24]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [26]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together